// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbXQPT3y0Ggn_YXTJ4ExSdzv9o_yCam8c',
    appId: '1:1021445040184:web:fa02770adc7ed06cb4decd',
    messagingSenderId: '1021445040184',
    projectId: 'fluttercli-7e47b',
    authDomain: 'fluttercli-7e47b.firebaseapp.com',
    storageBucket: 'fluttercli-7e47b.appspot.com',
    measurementId: 'G-REYXBFJCF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmc3I80pznrFyxwps_Rd4awtN1zEGdG_g',
    appId: '1:1021445040184:android:ebd76527ca751c1fb4decd',
    messagingSenderId: '1021445040184',
    projectId: 'fluttercli-7e47b',
    storageBucket: 'fluttercli-7e47b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQj_2EXk-zKRVgCYgDPUgknMqJKRuEy2g',
    appId: '1:1021445040184:ios:947f525bdee18ba5b4decd',
    messagingSenderId: '1021445040184',
    projectId: 'fluttercli-7e47b',
    storageBucket: 'fluttercli-7e47b.appspot.com',
    iosBundleId: 'com.example.flutterCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQj_2EXk-zKRVgCYgDPUgknMqJKRuEy2g',
    appId: '1:1021445040184:ios:5c79b19c52654f2ab4decd',
    messagingSenderId: '1021445040184',
    projectId: 'fluttercli-7e47b',
    storageBucket: 'fluttercli-7e47b.appspot.com',
    iosBundleId: 'com.example.flutterCli.RunnerTests',
  );
}
